version: '3'

services:
  mongodb:
    image: mongo:4.4.1
    container_name: mongo-4
    volumes:
    - 'mongo-data:/data'
    environment:
    - MONGO_INITDB_ROOT_USERNAME=sigl2021
    - MONGO_INITDB_ROOT_PASSWORD=sigl2021
    ports:
    - '27017:27017'

volumes: 
  mongo-data:
    external: 
      true
